---
##
## Notify if fridge or freezer door is open for mor then 2 minutes
##

alias: Fridge & Freezer doors open
trigger:
  - platform: state
    entity_id: binary_sensor.refrigerator_sensor
    from: 'off'
    to: 'on'
    for:
      minutes: 2
  - platform: state
    entity_id: binary_sensor.freezer_door
    from: 'off'
    to: 'on'
    for:
      minutes: 2
action:
  service: notify.notify
  data_template:
    title: "Your {{ trigger.to_state.attributes.friendly_name }} is open"
    message: "You might want to close the {{ trigger.to_state.attributes.friendly_name }}"
