---
##
## Automation to do certain things when arriving home
##

alias: Just arrived
trigger:
  - platform: state
    entity_id: person.aron
    to: 'home'
condition:
  - condition: numeric_state
    entity_id: sensor.fibaro_sensor_luminance
    below: 50
action:
  - service: light.turn_on
    entity_id:
      - group.kitchen_lights
      - light.livingroom_floor
      - light.bedroom_drawer
      - light.tv_lightstrip
      - light.office
      - light.entrance

