---
##
## Automation to turn off scene when turning off tv
##

alias: "Tv idle"
initial_state: on
trigger:
  - platform: state
    entity_id:  media_player.chromecast
    from: 'playing'
    to: 'idle'
  - platform: state
    entity_id:  media_player.chromecast
    from: 'playing'
    to: 'off'
  - platform: state
    entity_id:  media_player.chromecast
    from: 'idle'
    to: 'off'
condition:
  - condition: numeric_state
    entity_id: sensor.fibaro_system_motion_sensor_luminance
    below: '50'
action:
    service: scene.turn_on
    entity_id: scene.tv_idle
