version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    network_mode: bridge
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./srv/portainer/data:/data
    ports:
      - 9000:9000

  home-assistant:
    image: homeassistant/home-assistant:0.80.3
    container_name: home-assistant
    restart: always
    volumes:
      - ./home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0:/dev/zwave

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    environment:
      - PGID=0
      - PUID=0
    ports:
      - 1883:1883
      - 9001:9001

  deconz:
    image: marthoc/deconz:amd64-2.05.47
    container_name: deconz
    restart: unless-stopped
    volumes:
      - ./deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443

  nginx:
    image: nginx:1.13.11
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certificates:/etc/letsencrypt
      - ./nginx/letsencrypt:/data/letsencrypt
    ports:
      - 80:80
      - 443:443

  appdaemon:
    image: acockburn/appdaemon:latest
    container_name: appdaemon
    restart: always
    volumes:
      - ./appdaemon:/conf/
    ports:
      - 5050:5050
