---
##
## Turn on lights when luminance value is below 50
##

alias: Turn on lights when dark
trigger:
  - platform: numeric_state
    entity_id: sensor.fibaro_system_motion_sensor_luminance
    below: '50'
condition:
  - condition: state
    entity_id: person.aron
    state: home
  - condition: time
    after: '15:00:00'
    before: '00:00:00'
action:
  - service: light.turn_on
    entity_id:
      - light.kitchen_lights
      - light.livingroom_floor
      - light.bedroom_drawer
      - light.tv
      - light.office
      - light.entrance
