homeassistant:
  name: ahomie
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 143
  unit_system: metric
  time_zone: Europe/Stockholm
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:
discovery:
conversation:
history:
logbook:
map:
sun:
updater:
ios:
notify:

http:
  base_url: !secret http_base_url
  api_password: !secret http_password
  use_x_forwarded_for: true

# Text to speech
tts:
  - platform: google

zwave:
  usb_path: /dev/zwave
