homeassistant:
  name: ahomie
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 143
  unit_system: metric
  time_zone: Europe/Stockholm
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest

# Enables configuration UI
config:
conversation:
history:
logbook:
map:
sun:
updater:
ios:
notify:
system_health:

http:
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies: !secret http_ip_range

lovelace:
  mode: yaml

person:
  - name: Aron
    id: arontracker
    device_trackers:
      - device_tracker.presence_aron

tts:
  - platform: google

zwave:
  usb_path: /dev/zwave
  polling_interval: 30000

deconz:
  host: deconz
  port: 8080
