homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 143
  unit_system: metric
  time_zone: Europe/Stockholm
  external_url: !secret http_base_url
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest

# Enables configuration UI
config:
conversation:
history:
logbook:
map:
sun:
updater:
ios:
notify:
system_health:
mobile_app:
logger:
  default: info

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret http_ip_range

lovelace:
  mode: yaml

tts:
  - platform: google_translate

zha:
#  usb_path: /dev/zigbee
#  radio_type: deconz

hacs:
  token: !secret github_token
  appdaemon: true

browser_mod:
  devices:
    c0f2b05e-70f3a1c0:
      name: macbook
