title: ' '
resources: !include_dir_list lovelace/resources
views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/living-room.yaml
  - !include lovelace/views/bedroom.yaml
  - !include lovelace/views/kitchen.yaml
  - !include lovelace/views/vacuum.yaml
  - !include lovelace/views/alarm.yaml
