title: ' '
resources: !include_dir_list lovelace/resources
button_card_templates: !include lovelace/templates/button_card_templates.yaml
decluttering_templates: !include lovelace/templates/decluttering_card_templates.yaml
views:
  - !include lovelace/views/home_view.yaml
