##
## Lights
##


homeassistant:
  customize:
    automation.turn_on_lights_when_dark:
      hidden: false
    sensor.daylight:
      hidden: true
    light.livingroom_floor:
      friendly_name: Living room floor light
    light.bedroom_drawer:
      friendly_name: Bedroom drawer light
    light.livingroom_ceiling:
      friendly_name: Living room ceiling light

light:
  - platform: group
    name: Kitchen Lights Group
    entities:
      - light.kitchen_lights_zha
      - light.kitchen_table

  - platform: group
    name: Living Room Lights Group
    entities:
      - light.livingroom_floor
      - light.tv_lightstrip
      - light.livingroom_ceiling
      - light.office

  - platform: group
    name: Bedroom Lights Group
    entities:
      - light.bedroom_drawer
      - light.bedroom_ceiling

  - platform: group
    name: All Lights Group
    entities:
      - light.bedroom_lights_group
      - light.kitchen_lights_group
      - light.living_room_lights_group
      - light.entrance
      - light.closet
