##
## Lights
##


homeassistant:
  customize:
    automation.turn_on_lights_when_dark:
      hidden: false
    sensor.daylight:
      hidden: true

light:
  - platform: mqtt
    name: "Tv lamp"
    command_topic: "cmnd/sonoff/power"
    state_topic: "stat/sonoff/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Bedroom drawer lamp"
    command_topic: "cmnd/sonoff4/power"
    state_topic: "stat/sonoff4/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

group:
  Lights:
    - light.tv_lamp
    - light.bedroom_drawer_lamp
    - light.osramstrip
    - light.office_lamp


automation:
  - id: turn_on_lights
    alias: Turn on lights when dark
    initial_state: on
    trigger:
      - platform: numeric_state
        entity_id: sensor.fibaro_system_motion_sensor_luminance
        below: '50'
    condition:
      - condition: state
        entity_id: person.aron
        state: home
      - condition: time
        after: '15:00:00'
        before: '00:00:00'
    action:
      - service: light.turn_on
        entity_id:
          - light.tv_lamp
          - light.bedroom_drawer_lamp
          - light.osramstrip
