##
## Lights
##


homeassistant:
  customize:
    automation.turn_on_lights_when_dark:
      hidden: false
    sensor.daylight:
      hidden: true
    light.livingroom_floor:
      friendly_name: Living room floor light
    light.bedroom_drawer:
      friendly_name: Bedroom drawer light
    light.livingroom_ceiling:
      friendly_name: Living room ceiling light

light:
  - platform: mqtt
    name: "livingroom_floor"
    command_topic: "cmnd/sonoff/power"
    state_topic: "stat/sonoff/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "bedroom_drawer"
    command_topic: "cmnd/sonoff4/power"
    state_topic: "stat/sonoff4/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: group
    name: Kitchen Lights Group
    entities:
      - light.kitchen_lights_zha
      - light.kitchen_table

  - platform: group
    name: Living Room Lights Group
    entities:
      - light.livingroom_floor
      - light.tv_lightstrip
      - light.livingroom_ceiling
      - light.office

  - platform: group
    name: Bedroom Lights Group
    entities:
      - light.bedroom_drawer
      - light.bedroom_ceiling

switch:
  - platform: template
    switches:
      all_lights:
        value_template: >
          {% set domain = 'light' %}
          {% set state = 'on' %}
          {{ states[domain] | selectattr('state','eq', state) | list | count > 0 }}
        turn_on:
          service: shell_command.nop
        turn_off:
          service: light.turn_off
          data:
            entity_id: all
