##
## Door / Window Sensors
##

homeassistant:
  customize:
    automation.doors_open:
      hidden: true
    binary_sensor.refrigerator_door:
      friendly_name: Fridge door
      icon: mdi:fridge
    binary_sensor.freezer_door:
      friendly_name: Freezer door
      icon: mdi:fridge

automation:
  - alias: doors_open
    trigger:
      - platform: state
        entity_id: binary_sensor.refrigerator_door
        from: 'off'
        to: 'on'
        for:
          minutes: 2
      - platform: state
        entity_id: binary_sensor.freezer_door
        from: 'off'
        to: 'on'
        for:
          minutes: 2
    action:
      service: notify.notify
      data_template:
        title: "Your {{ trigger.to_state.attributes.friendly_name }} is open"
        message: "You might want to close that door."
