##
## Media players
##

cast:
  media_player:
  - host: !secret chromecast_ip
  - host: !secret homemini_ip

automation:
  - id: tv_mode_on
    alias: "Tv playing"
    initial_state: on
    trigger:
      - platform: state
        entity_id:  media_player.chromecast
        from: 'idle'
        to: 'playing'
      - platform: state
        entity_id:  media_player.chromecast
        from: 'paused'
        to: 'playing'
      - platform: state
        entity_id:  media_player.chromecast
        from: 'off'
        to: 'playing'
    condition:
      - condition: numeric_state
        entity_id: sensor.fibaro_system_motion_sensor_luminance
        below: '50'
    action:
        service: scene.turn_on
        entity_id: scene.tv_on
  - id: tv_mode_idle
    alias: "Tv idle"
    initial_state: on
    trigger:
      - platform: state
        entity_id:  media_player.chromecast
        from: 'playing'
        to: 'idle'
      - platform: state
        entity_id:  media_player.chromecast
        from: 'playing'
        to: 'off'
      - platform: state
        entity_id:  media_player.chromecast
        from: 'idle'
        to: 'off'
    condition:
      - condition: numeric_state
        entity_id: sensor.fibaro_system_motion_sensor_luminance
        below: '50'
    action:
        service: scene.turn_on
        entity_id: scene.tv_idle
