---
##
## Persons
##
homeassistant:
  customize:
    person.aron:
      entity_picture: "/local/Image.png"

person:
  - name: Aron
    id: aron
    device_trackers:
      - device_tracker.arons_iphone
