##
## Devices for presence
##

homeassistant:
  customize:
    device_tracker.iphone:
      friendly_name: Aron
      icon: mdi:human-male
    sensor.iphone_battery_level:
      friendly_name: Battery
      icon: mdi:battery

# Presence
sensor:
  - platform: mqtt
    name: aron_iphone_bt
    state_topic: 'monitor/home/owner/apartment/18:65:90:2F:CC:E4'
    value_template: >
     {% if float(value_json.confidence) > 0 %}
      home
     {% else %}
      not_home
     {% endif %}
    json_attributes_topic: 'monitor/home/owner/apartment/18:65:90:2F:CC:E4'

# Aproximity
proximity:
  home_aron:
    zone: home
    devices:
      - device_tracker.iphone
    tolerance: 50

automation:
  - alias: Notify presence change
    initial_state: on
    trigger:
      - platform: state
        entity_id: person.aron
    action:
      - service: notify.notify
        data_template:
          message: >
            Aron just changed from {{ trigger.from_state.state }}
            to {{ trigger.to_state.state }}


