##
## Devices for presence
##

homeassistant:
  customize:
    device_tracker.arons_iphone:
      friendly_name: Aron
      icon: mdi:human-male
    sensor.battery_level:
      friendly_name: Battery
      icon: mdi:battery



