---
##
## Package for play radio stations
## Used together with alarm clock package
##

homeassistant:
  customize:
    script.radio:
      action_name: Play
    script.radio_off:
      action_name: Stop

group:
  radio:
    name: Radio
    entities:
    - input_select.radio_station
    - input_select.chromecast_radio
    - script.radio
    - script.radio_off
    - input_number.volume_radio

input_select:
  radio_station:
    name: 'Select Radio Station:'
    options:
      - SR P3
      - Fresh 92-7
      - DI Chill & Tropical House
      - DI Disco House
      - DI Funky House
  chromecast_radio:
    name: 'Select Speakers:'
    options:
      - Bedroom
      - Kitchen
    initial: Bedroom
    icon: mdi:speaker-wireless

input_number:
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05

automation:
  - alias: Listen Radio
    trigger:
      - platform: state
        entity_id: input_select.radio_station
    action:
      - service: script.radio
  - alias: Set Chromecast radio volume
    trigger:
      platform: state
      entity_id: input_number.volume_radio
    action:
      service: media_player.volume_set
      data_template:
        entity_id: >
          {% if is_state("input_select.chromecast_radio", "Bedroom") %} media_player.bedroom_google_home
          {% elif is_state("input_select.chromecast_radio", "Kitchen") %} media_player.kitchen_sonos_sonos
          {% endif %}
        volume_level: '{{ states.input_number.volume_radio.state }}'

script:
  radio:
    alias: Radio
    sequence:
    - service: media_player.volume_set
      data_template:
        entity_id: >
          {% if is_state("input_select.chromecast_radio", "Bedroom") %} media_player.bedroom_google_home
          {% elif is_state("input_select.chromecast_radio", "Kitchen") %} media_player.kitchen_sonos
          {% endif %}
        volume_level: '{{ states.input_number.volume_radio.state }}'
    - service: media_player.play_media
      data_template:
        entity_id: >
          {% if is_state("input_select.chromecast_radio", "Bedroom") %} media_player.bedroom_google_home
          {% elif is_state("input_select.chromecast_radio", "Kitchen") %} media_player.kitchen_sonos
          {% endif %}
        media_content_id: >
          {% if is_state("input_select.radio_station", "SR P3") %} http://sverigesradio.se/topsy/direkt/srapi/164.mp3
          {% elif is_state("input_select.radio_station", "Fresh 92-7") %} http://live.fresh927.com.au/freshmp3
          {% elif is_state("input_select.radio_station", "DI Chill & Tropical House") %} http://pub1.diforfree.org:8000/di_chillntropicalhouse_hi
          {% elif is_state("input_select.radio_station", "DI Disco House") %} http://pub1.diforfree.org:8000/di_discohouse_hi
          {% elif is_state("input_select.radio_station", "DI Funky House") %} http://pub1.diforfree.org:8000/di_funkyhouse_hi
          {% endif %}
        media_content_type: 'audio/mp4'
  radio_off:
    alias: Radio off
    sequence:
      - service: media_player.media_stop
        data_template:
          entity_id: >
            {% if is_state("input_select.chromecast_radio", "Bedroom") %} media_player.bedroom_google_home
            {% elif is_state("input_select.chromecast_radio", "Kitchen") %} media_player.kitchen_sonos
            {% endif %}
