##
## Sensors
##

homeassistant:
  customize:
    automation.smoke:
      hidden: true
    binary_sensor.sf20_smoke_sensor:
      friendly_name: Smoke Sensor
      icon: mdi:smoke-detector
    automation.doors_open:
      hidden: true
    binary_sensor.refrigerator_sensor:
      friendly_name: Fridge door
      icon: mdi:fridge
    binary_sensor.freezer_sensor:
      friendly_name: Freezer door
      icon: mdi:fridge
    automation.water_leak:
      hidden: true
    binary_sensor.water:
      friendly_name: Water Leak
      icon: mdi:water
    sensor.bedroom_temperature:
      friendly_name: Bedroom Pressure
    sensor.bedroom_temperature_2:
      friendly_name: Bedroom Humidity
    sensor.bedroom_temperature_3:
      friendly_name: Bedroom Temperature
    sensor.kitchen_temperature:
      friendly_name: Kitchen Temperature
    sensor.kitchen_temperature_2:
      friendly_name: Kitchen Humidity
    sensor.kitchen_temperature_3:
      friendly_name: Kitchen Pressure
    sensor.fibaro_system_motion_sensor_luminance:
      friendly_name: Living Room luminance
      icon: mdi:lightbulb-outline
    sensor.fibaro_system_motion_sensor_temperature:
      friendly_name: Living Room temperature
    sensor.living_room_motion:
      icon: mdi:run

### Fibaro Motion Detector status
sensor:
  - platform: template
    sensors:
      living_room_motion:
        friendly_name: "Motion"
        value_template: >-
          {% set state = states('sensor.fibaro_system_motion_sensor_burglar') %}
          {% if state == '0' %}
            Idle
          {% elif state == '8' %}
            Motion Detected
          {% elif state == '3' %}
            Tamper
          {% elif state == '254' %}
            Sleeping
          {% else %}
            {{ state|title }}
          {% endif %}

group:
  living_room_sensors:
    name:  Living Room Sensors
    entities:
      - sensor.fibaro_system_motion_sensor_temperature
      - sensor.fibaro_system_motion_sensor_luminance
      - sensor.living_room_motion
