##
## Sensors
##

homeassistant:
  customize:
    automation.smoke:
      hidden: true
    binary_sensor.sf20_smoke_sensor:
      friendly_name: Smoke Sensor
      icon: mdi:smoke-detector
    automation.doors_open:
      hidden: true
    binary_sensor.refrigerator_sensor:
      friendly_name: Fridge Door
      icon: mdi:fridge
    binary_sensor.freezer_sensor:
      friendly_name: Freezer Door
      icon: mdi:fridge
    automation.water_leak:
      hidden: true
    binary_sensor.water:
      friendly_name: Water Leak
      icon: mdi:water
    sensor.fibaro_system_motion_sensor_luminance:
      friendly_name: Living Room luminance
      icon: mdi:lightbulb-outline
    sensor.fibaro_system_motion_sensor_temperature:
      friendly_name: Living Room temperature
    sensor.living_room_motion:
      icon: mdi:run

sensor:
  - platform: min_max
    name: "Average Indoor Temperature"
    type: "mean"
    round_digits: 1
    entity_ids:
      - sensor.fibaro_sensor_temperature
      - sensor.kitchen_temperature
      - sensor.bedroom_temperature
