##
## Sensors
##

homeassistant:
  customize:
    automation.smoke:
      hidden: true
    binary_sensor.sf20_smoke_sensor:
      friendly_name: Smoke Sensor
      icon: mdi:smoke-detector
    automation.doors_open:
      hidden: true
    binary_sensor.refrigerator_sensor:
      friendly_name: Fridge door
      icon: mdi:fridge
    binary_sensor.freezer_sensor:
      friendly_name: Freezer door
      icon: mdi:fridge
    automation.water_leak:
      hidden: true
    binary_sensor.water:
      friendly_name: Water Leak
      icon: mdi:water
    sensor.bedroom_temperature:
      friendly_name: Bedroom Pressure
    sensor.bedroom_temperature_2:
      friendly_name: Bedroom Humidity
    sensor.bedroom_temperature_3:
      friendly_name: Bedroom Temperature
    sensor.kitchen_temperature:
      friendly_name: Kitchen Temperature
    sensor.kitchen_temperature_2:
      friendly_name: Kitchen Humidity
    sensor.kitchen_temperature_3:
      friendly_name: Kitchen Pressure

automation:
  - alias: smoke
    trigger:
      - platform: state
        entity_id: binary_sensor.smoke
        from: 'off'
        to: 'on'
        for:
          seconds: 5
    action:
      service: notify.notify
      data_template:
        title: "{{ trigger.to_state.attributes.friendly_name }} is detecting Smoke"
        message: "You might want to check that out."
  - alias: doors_open
    trigger:
      - platform: state
        entity_id: binary_sensor.refrigerator_door
        from: 'off'
        to: 'on'
        for:
          minutes: 2
      - platform: state
        entity_id: binary_sensor.freezer_door
        from: 'off'
        to: 'on'
        for:
          minutes: 2
    action:
      service: notify.notify
      data_template:
        title: "Your {{ trigger.to_state.attributes.friendly_name }} is open"
        message: "You might want to close that door."
  - alias: water_leak
    trigger:
      - platform: state
        entity_id: binary_sensor.water_leak
        from: 'off'
        to: 'on'
        for:
          seconds: 30
    action:
      service: notify.notify
      data_template:
        title: "{{ trigger.to_state.attributes.friendly_name }} is detecting water"
        message: "You might want to check that out."
