##
## Smart Plugs
##

homeassistant:
  customize:
    switch.osram_plug_1:
      friendly_name: Switch 1
      icon: mdi:power-plug
    switch.osram_plug_2:
      friendly_name: Switch 2
      icon: mdi:power-plug
