---
##
## Automation for turn lights on when detect motion in closet
##

alias: Turn on closet light
initial_state: on
trigger:
  platform: state
  entity_id: binary_sensor.closet_presence
  to: 'on'
action:
  - service: light.turn_on
    data:
      entity_id: light.closet
