##
## Devices
##

homeassistant:
  customize:
    device_tracker.iphone:
      friendly_name: Aron
      icon: mdi:human-male
    sensor.iphone_battery_level:
      friendly_name: Battery
      icon: mdi:battery
