##
## ssl cert expiry date
## secret: ssl-cert-check -b -c /etc/letsencrypt/live/yoururl.duckdns.org/cert.pem | awk '{ print $NF }'
## apt-get install ssl-cert-check
##

homeassistant:
  customize:

sensor:
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: !secret ssl_command

group:
  SSL Sensor:
    - sensor.ssl_cert_expiry
